import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import { KPICard } from './KPICard';
import { TrendChart } from './TrendChart';
import { TransactionTable } from './TransactionTable';
import { CSVExportModal } from './CSVExportModal';

type Transaction = { id: number | string; amount: number; category: string; status: string; date: string; user_id?: string };

export const DashboardPage = () => {
  const { token, logout } = useAuth();
  const [transactions, setTransactions] = useState<Transaction[]>([]); const [allTransactions, setAllTransactions] = useState<Transaction[]>([]); const [error, setError] = useState(''); const [showExport, setShowExport] = useState(false); const [exportColumns, setExportColumns] = useState(['date', 'amount', 'category', 'status']); const [filters, setFilters] = useState({ skip: 0, limit: 25, search: '', category: '', status: '', sortBy: 'date', sortOrder: 'desc' });
  const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:5001'; const headers = useMemo(() => ({ Authorization: `Bearer ${token}` }), [token]);
  useEffect(() => { const params = new URLSearchParams(Object.entries(filters).map(([key, value]) => [key, String(value)])).toString(); axios.get(`${apiUrl}/api/transactions?${params}`, { headers }).then((res) => setTransactions(res.data.transactions || [])).catch((err) => { if (err.response?.status === 401) { setError('Your session has expired. Please sign in again.'); logout(); } else setError('Could not load transactions. Check that the backend is running.'); }); }, [apiUrl, filters, headers, logout]);
  useEffect(() => { axios.get(`${apiUrl}/api/transactions?skip=0&limit=1000&sortBy=date&sortOrder=asc`, { headers }).then((res) => setAllTransactions(res.data.transactions || [])).catch(() => undefined); }, [apiUrl, headers]);
  const analytics = useMemo(() => { const source = allTransactions.length ? allTransactions : transactions; const revenue = source.filter((tx) => tx.category === 'Revenue').reduce((sum, tx) => sum + Number(tx.amount || 0), 0); const expenses = source.filter((tx) => tx.category === 'Expense').reduce((sum, tx) => sum + Number(tx.amount || 0), 0); const monthly = Array.from({ length: 12 }, (_, index) => ({ month: new Date(2024, index, 1).toLocaleString('en-IN', { month: 'short' }), revenue: 0, expenses: 0 })); source.forEach((tx) => { const month = new Date(tx.date).getMonth(); if (month >= 0 && month < 12) monthly[month][tx.category === 'Revenue' ? 'revenue' : 'expenses'] += Number(tx.amount || 0); }); return { revenue, expenses, balance: revenue - expenses, monthly }; }, [allTransactions, transactions]);
  const exportCsv = () => axios.post(`${apiUrl}/api/export/csv`, { columns: exportColumns, filters }, { headers, responseType: 'blob' }).then((res) => { const url = window.URL.createObjectURL(new Blob([res.data])); const link = document.createElement('a'); link.href = url; link.download = 'transactions.csv'; link.click(); window.URL.revokeObjectURL(url); setShowExport(false); }).catch(() => setError('Your CSV could not be generated. Please try again.'));
  const setSort = (field: string) => setFilters({ ...filters, sortBy: field, sortOrder: filters.sortBy === field && filters.sortOrder === 'desc' ? 'asc' : 'desc', skip: 0 });
  const activity = transactions.slice(0, 3);
  return <div className="penta-app"><aside className="penta-sidebar"><div className="penta-brand"><b>↻</b> Penta</div><nav><a className="selected" href="#dashboard">▦ <span>Dashboard</span></a><a href="#transactions">▣ <span>Transactions</span></a><a href="#wallet">▱ <span>Wallet</span></a><a href="#overview">▧ <span>Analytics</span></a><a href="#personal">♙ <span>Personal</span></a><a href="#messages">✉ <span>Message</span></a></nav><a className="nav-setting" href="#settings">⚙ <span>Setting</span></a></aside><main className="penta-main" id="dashboard"><header className="penta-header"><h1>Dashboard</h1><div className="penta-tools"><label className="header-search">Search... <input aria-label="Global search" /></label><button className="bell" aria-label="Notifications">♧</button><button className="profile-dot">A</button><button className="tiny-logout" onClick={logout}>Log out</button></div></header>{error && <p className="penta-alert" role="alert">! {error}<button onClick={() => setError('')}>×</button></p>}
    <section className="penta-metrics"><KPICard icon="▣" title="Balance" value={analytics.balance} tone="neutral" /><KPICard icon="▤" title="Revenue" value={analytics.revenue} tone="income" /><KPICard icon="▰" title="Expenses" value={analytics.expenses} tone="expense" /><KPICard icon="●" title="Savings" value={Math.max(0, analytics.balance)} tone="income" /></section>
    <section className="penta-insights"><article className="penta-chart" id="overview"><div className="penta-card-title"><h2>Overview</h2><span><i className="green-dot" /> Income <i className="yellow-dot" /> Expenses <button>Monthly⌄</button></span></div><TrendChart data={analytics.monthly} /></article><article className="recent-card"><div className="penta-card-title"><h2>Recent Transaction</h2><a href="#transactions">See all</a></div>{activity.map((tx) => <div className="mini-tx" key={tx.id}><span className="mini-avatar">{(tx.user_id || 'U').slice(-1)}</span><div><small>Transfer {tx.category === 'Revenue' ? 'from' : 'to'}</small><b>{tx.user_id || 'User account'}</b></div><strong className={tx.category === 'Revenue' ? 'positive' : 'negative'}>{tx.category === 'Revenue' ? '+' : '−'}₹{tx.amount.toLocaleString('en-IN')}</strong></div>)}</article></section>
    <section className="penta-transactions" id="transactions"><div className="transaction-head"><h2>Transactions</h2><div className="table-tools"><label className="penta-search">Search for anything...<input type="search" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value, skip: 0 })} /></label><label className="penta-select">Type <select value={filters.category} onChange={(event) => setFilters({ ...filters, category: event.target.value, skip: 0 })}><option value="">All</option><option value="Revenue">Revenue</option><option value="Expense">Expense</option></select></label><label className="penta-select">Status <select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value, skip: 0 })}><option value="">All</option><option value="Paid">Paid</option><option value="Pending">Pending</option></select></label><button className="export-small" onClick={() => setShowExport(true)}>⇩ Export</button></div></div><TransactionTable data={transactions} onSort={setSort} sortBy={filters.sortBy} sortOrder={filters.sortOrder} />{!error && !transactions.length && <p className="empty-state">No transactions match these filters.</p>}</section>{showExport && <CSVExportModal selected={exportColumns} onChange={setExportColumns} onClose={() => setShowExport(false)} onExport={exportCsv} />}</main></div>;
};
